sudo: required
services:
  - docker

before_install:
  - docker build -t vinsin44/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vinsin44/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env-2"
  bucket_name: "elasticbeanstalk-us-east-1-240007032654"
  bucket_path: "docker"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY 